/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscriptionOffersRouteImport } from './routes/subscription-offers'
import { Route as RoleRouteImport } from './routes/role'
import { Route as PriceIntelligenceRouteImport } from './routes/price-intelligence'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as MapRouteImport } from './routes/map'
import { Route as HelpRouteImport } from './routes/help'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackIdRouteImport } from './routes/track.$id'
import { Route as SubscriptionPaymentIdRouteImport } from './routes/subscription-payment.$id'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as PaymentIdRouteImport } from './routes/payment.$id'
import { Route as FarmerDashboardRouteImport } from './routes/farmer.dashboard'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthFarmerRouteImport } from './routes/auth.farmer'
import { Route as AuthConsumerRouteImport } from './routes/auth.consumer'

const SubscriptionOffersRoute = SubscriptionOffersRouteImport.update({
  id: '/subscription-offers',
  path: '/subscription-offers',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleRoute = RoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => rootRouteImport,
} as any)
const PriceIntelligenceRoute = PriceIntelligenceRouteImport.update({
  id: '/price-intelligence',
  path: '/price-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackIdRoute = TrackIdRouteImport.update({
  id: '/track/$id',
  path: '/track/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionPaymentIdRoute = SubscriptionPaymentIdRouteImport.update({
  id: '/subscription-payment/$id',
  path: '/subscription-payment/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentIdRoute = PaymentIdRouteImport.update({
  id: '/payment/$id',
  path: '/payment/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerDashboardRoute = FarmerDashboardRouteImport.update({
  id: '/farmer/dashboard',
  path: '/farmer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthFarmerRoute = AuthFarmerRouteImport.update({
  id: '/auth/farmer',
  path: '/auth/farmer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConsumerRoute = AuthConsumerRouteImport.update({
  id: '/auth/consumer',
  path: '/auth/consumer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/help': typeof HelpRoute
  '/map': typeof MapRoute
  '/marketplace': typeof MarketplaceRoute
  '/orders': typeof OrdersRoute
  '/price-intelligence': typeof PriceIntelligenceRoute
  '/role': typeof RoleRoute
  '/subscription-offers': typeof SubscriptionOffersRoute
  '/auth/consumer': typeof AuthConsumerRoute
  '/auth/farmer': typeof AuthFarmerRoute
  '/auth/login': typeof AuthLoginRoute
  '/farmer/dashboard': typeof FarmerDashboardRoute
  '/payment/$id': typeof PaymentIdRoute
  '/product/$id': typeof ProductIdRoute
  '/subscription-payment/$id': typeof SubscriptionPaymentIdRoute
  '/track/$id': typeof TrackIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/help': typeof HelpRoute
  '/map': typeof MapRoute
  '/marketplace': typeof MarketplaceRoute
  '/orders': typeof OrdersRoute
  '/price-intelligence': typeof PriceIntelligenceRoute
  '/role': typeof RoleRoute
  '/subscription-offers': typeof SubscriptionOffersRoute
  '/auth/consumer': typeof AuthConsumerRoute
  '/auth/farmer': typeof AuthFarmerRoute
  '/auth/login': typeof AuthLoginRoute
  '/farmer/dashboard': typeof FarmerDashboardRoute
  '/payment/$id': typeof PaymentIdRoute
  '/product/$id': typeof ProductIdRoute
  '/subscription-payment/$id': typeof SubscriptionPaymentIdRoute
  '/track/$id': typeof TrackIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/help': typeof HelpRoute
  '/map': typeof MapRoute
  '/marketplace': typeof MarketplaceRoute
  '/orders': typeof OrdersRoute
  '/price-intelligence': typeof PriceIntelligenceRoute
  '/role': typeof RoleRoute
  '/subscription-offers': typeof SubscriptionOffersRoute
  '/auth/consumer': typeof AuthConsumerRoute
  '/auth/farmer': typeof AuthFarmerRoute
  '/auth/login': typeof AuthLoginRoute
  '/farmer/dashboard': typeof FarmerDashboardRoute
  '/payment/$id': typeof PaymentIdRoute
  '/product/$id': typeof ProductIdRoute
  '/subscription-payment/$id': typeof SubscriptionPaymentIdRoute
  '/track/$id': typeof TrackIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/help'
    | '/map'
    | '/marketplace'
    | '/orders'
    | '/price-intelligence'
    | '/role'
    | '/subscription-offers'
    | '/auth/consumer'
    | '/auth/farmer'
    | '/auth/login'
    | '/farmer/dashboard'
    | '/payment/$id'
    | '/product/$id'
    | '/subscription-payment/$id'
    | '/track/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/help'
    | '/map'
    | '/marketplace'
    | '/orders'
    | '/price-intelligence'
    | '/role'
    | '/subscription-offers'
    | '/auth/consumer'
    | '/auth/farmer'
    | '/auth/login'
    | '/farmer/dashboard'
    | '/payment/$id'
    | '/product/$id'
    | '/subscription-payment/$id'
    | '/track/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/help'
    | '/map'
    | '/marketplace'
    | '/orders'
    | '/price-intelligence'
    | '/role'
    | '/subscription-offers'
    | '/auth/consumer'
    | '/auth/farmer'
    | '/auth/login'
    | '/farmer/dashboard'
    | '/payment/$id'
    | '/product/$id'
    | '/subscription-payment/$id'
    | '/track/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  HelpRoute: typeof HelpRoute
  MapRoute: typeof MapRoute
  MarketplaceRoute: typeof MarketplaceRoute
  OrdersRoute: typeof OrdersRoute
  PriceIntelligenceRoute: typeof PriceIntelligenceRoute
  RoleRoute: typeof RoleRoute
  SubscriptionOffersRoute: typeof SubscriptionOffersRoute
  AuthConsumerRoute: typeof AuthConsumerRoute
  AuthFarmerRoute: typeof AuthFarmerRoute
  AuthLoginRoute: typeof AuthLoginRoute
  FarmerDashboardRoute: typeof FarmerDashboardRoute
  PaymentIdRoute: typeof PaymentIdRoute
  ProductIdRoute: typeof ProductIdRoute
  SubscriptionPaymentIdRoute: typeof SubscriptionPaymentIdRoute
  TrackIdRoute: typeof TrackIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscription-offers': {
      id: '/subscription-offers'
      path: '/subscription-offers'
      fullPath: '/subscription-offers'
      preLoaderRoute: typeof SubscriptionOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role': {
      id: '/role'
      path: '/role'
      fullPath: '/role'
      preLoaderRoute: typeof RoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/price-intelligence': {
      id: '/price-intelligence'
      path: '/price-intelligence'
      fullPath: '/price-intelligence'
      preLoaderRoute: typeof PriceIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$id': {
      id: '/track/$id'
      path: '/track/$id'
      fullPath: '/track/$id'
      preLoaderRoute: typeof TrackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription-payment/$id': {
      id: '/subscription-payment/$id'
      path: '/subscription-payment/$id'
      fullPath: '/subscription-payment/$id'
      preLoaderRoute: typeof SubscriptionPaymentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/$id': {
      id: '/payment/$id'
      path: '/payment/$id'
      fullPath: '/payment/$id'
      preLoaderRoute: typeof PaymentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/dashboard': {
      id: '/farmer/dashboard'
      path: '/farmer/dashboard'
      fullPath: '/farmer/dashboard'
      preLoaderRoute: typeof FarmerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/farmer': {
      id: '/auth/farmer'
      path: '/auth/farmer'
      fullPath: '/auth/farmer'
      preLoaderRoute: typeof AuthFarmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/consumer': {
      id: '/auth/consumer'
      path: '/auth/consumer'
      fullPath: '/auth/consumer'
      preLoaderRoute: typeof AuthConsumerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  HelpRoute: HelpRoute,
  MapRoute: MapRoute,
  MarketplaceRoute: MarketplaceRoute,
  OrdersRoute: OrdersRoute,
  PriceIntelligenceRoute: PriceIntelligenceRoute,
  RoleRoute: RoleRoute,
  SubscriptionOffersRoute: SubscriptionOffersRoute,
  AuthConsumerRoute: AuthConsumerRoute,
  AuthFarmerRoute: AuthFarmerRoute,
  AuthLoginRoute: AuthLoginRoute,
  FarmerDashboardRoute: FarmerDashboardRoute,
  PaymentIdRoute: PaymentIdRoute,
  ProductIdRoute: ProductIdRoute,
  SubscriptionPaymentIdRoute: SubscriptionPaymentIdRoute,
  TrackIdRoute: TrackIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
